---
# ESP32 BLE Hub
#
substitutions:
  project: Bluetooth Hub
  id: bluetooth_hub
  hostname: bluetooth-hub

  <<: !include common/substitutions/bluetooth_hub.yaml

<<: !include common/esphome/esp32_wrover.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  #use_address: bluetooth_hub.local

  # Using these as a precaution to ensure solid WiFi connectivity.
  #power_save_mode: none # Disable for ESP32
  manual_ip:
    static_ip: 10.0.20.13
    gateway: 10.0.20.1
    subnet: 255.255.255.0

<<: !include common/ota.yaml
<<: !include common/logger_info.yaml
#<<: !include common/logger_debug.yaml
<<: !include common/api.yaml

esp32_ble_tracker:
  # scan_parameters:
  #   interval: 160 ms
  #   window: 160 ms

# text_sensor:
#   - platform: ble_scanner
#     name: Bluetooth hub scanner
#     id: bluetooth_hub_scanner
#     on_value:
#       then:
#         - lambda: |-
#             parse_json(id(bluetooth_hub_scanner));
#             if (id(bluetooth_hub_scanner)["name"] != "") {
#               ESP_LOGI("main", "Value of my sensor: %s", id(bluetooth_hub_scanner)["name"].c_str());
#             }

sensor:
  # LYWSD03MMC $4 temperature Sensors
  # Flashed with custom firmware in Chrome at https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html
  # Settings:
  #   * "F"
  #   * Advertising Type: "Mi"
  #   * Click [Show all mi keys] to get MAC Address

  # Bedroom
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:23:ED:41"
    bindkey: "5119b4890c72bc66121278dca55df431"
    temperature:
      name: "Bedroom temperature"
      device_class: temperature
      state_class: measurement
      unit_of_measurement: "°C"
      accuracy_decimals: 1

    humidity:
      name: "Bedroom humidity"
      device_class: humidity
      state_class: measurement
      unit_of_measurement: "%"
      accuracy_decimals: 0

    battery_level:
      name: "Bedroom temperature battery"
      entity_category: diagnostic
      device_class: battery
      state_class: measurement
      unit_of_measurement: "%"
      accuracy_decimals: 0

  - platform: ble_rssi
    mac_address: "A4:C1:38:23:ED:41"
    name: "Bedroom temperature signal"
    disabled_by_default: true
    entity_category: diagnostic
    device_class: signal_strength
    state_class: measurement
    unit_of_measurement: dBm
    accuracy_decimals: 0

  # Family Room
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:BF:98:48"
    bindkey: "9e58510b59d2f2d386a15c3ae60bf59a"
    temperature:
      name: "Family Room temperature"
      device_class: temperature
      state_class: measurement
      unit_of_measurement: "°C"
      accuracy_decimals: 1

    humidity:
      name: "Family Room humidity"
      device_class: humidity
      state_class: measurement
      unit_of_measurement: "%"
      accuracy_decimals: 0

    battery_level:
      name: "Family Room temperature battery"
      entity_category: diagnostic
      device_class: battery
      state_class: measurement
      unit_of_measurement: "%"
      accuracy_decimals: 0

  - platform: ble_rssi
    mac_address: "A4:C1:38:BF:98:48"
    name: "Family Room temperature signal"
    disabled_by_default: true
    entity_category: diagnostic
    device_class: signal_strength
    state_class: measurement
    unit_of_measurement: dBm
    accuracy_decimals: 0

  # Garage
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:FA:00:36"
    bindkey: "98d8225995fdfb2a4d5110b08e2e0fc6"
    temperature:
      name: "Garage temperature"
      device_class: temperature
      state_class: measurement
      unit_of_measurement: "°C"
      accuracy_decimals: 1

    humidity:
      name: "Garage humidity"
      device_class: humidity
      state_class: measurement
      unit_of_measurement: "%"
      accuracy_decimals: 0

    battery_level:
      name: "Garage temperature battery"
      entity_category: diagnostic
      device_class: battery
      state_class: measurement
      unit_of_measurement: "%"
      accuracy_decimals: 0

  - platform: ble_rssi
    mac_address: "A4:C1:38:FA:00:36"
    name: "Garage temperature signal"
    disabled_by_default: true
    entity_category: diagnostic
    device_class: signal_strength
    state_class: measurement
    unit_of_measurement: dBm
    accuracy_decimals: 0

  # Guest room
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:03:EE:C7"
    bindkey: "9e58510b59d2f2d386a15c3ae60bf59a"
    temperature:
      name: "Guest room temperature"
      device_class: temperature
      state_class: measurement
      unit_of_measurement: "°C"
      accuracy_decimals: 1

    humidity:
      name: "Guest room humidity"
      device_class: humidity
      state_class: measurement
      unit_of_measurement: "%"
      accuracy_decimals: 0

    battery_level:
      name: "Guest room temperature battery"
      entity_category: diagnostic
      device_class: battery
      state_class: measurement
      unit_of_measurement: "%"
      accuracy_decimals: 0

  - platform: ble_rssi
    mac_address: "A4:C1:38:03:EE:C7"
    name: "Guest room temperature signal"
    disabled_by_default: true
    entity_category: diagnostic
    device_class: signal_strength
    state_class: measurement
    unit_of_measurement: dBm
    accuracy_decimals: 0

  # Lucas' Room
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:4C:90:2D"
    bindkey: "04d5ad30b0853cadaee54053f0032cee"
    temperature:
      name: "Lucas room temperature"
      device_class: temperature
      state_class: measurement
      unit_of_measurement: "°C"
      accuracy_decimals: 1

    humidity:
      name: "Lucas room humidity"
      device_class: humidity
      state_class: measurement
      unit_of_measurement: "%"
      accuracy_decimals: 0

    battery_level:
      name: "Lucas room temperature battery"
      entity_category: diagnostic
      device_class: battery
      state_class: measurement
      unit_of_measurement: "%"
      accuracy_decimals: 0

  - platform: ble_rssi
    mac_address: "A4:C1:38:4C:90:2D"
    name: "Lucas room temperature signal"
    disabled_by_default: true
    entity_category: diagnostic
    device_class: signal_strength
    state_class: measurement
    unit_of_measurement: dBm
    accuracy_decimals: 0

  # Upstairs bathroom
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:0E:D8:EA"
    bindkey: "a25c346de94877c61f3a948eb76ceab9"
    temperature:
      name: "Upstairs bathroom temperature"
      device_class: temperature
      state_class: measurement
      unit_of_measurement: "°C"
      accuracy_decimals: 1

    humidity:
      name: "Upstairs bathroom humidity"
      device_class: humidity
      state_class: measurement
      unit_of_measurement: "%"
      accuracy_decimals: 0

    battery_level:
      name: "Upstairs bathroom temperature battery"
      entity_category: diagnostic
      device_class: battery
      state_class: measurement
      unit_of_measurement: "%"
      accuracy_decimals: 0

  - platform: ble_rssi
    mac_address: "A4:C1:38:0E:D8:EA"
    name: "Upstairs bathroom temperature signal"
    disabled_by_default: true
    entity_category: diagnostic
    device_class: signal_strength
    state_class: measurement
    unit_of_measurement: dBm
    accuracy_decimals: 0


  # Old round Celsius-only Sensor
  # - platform: ble_rssi
  #   mac_address: $temp1_mac
  #   id: ${temp1}_rssi
  #   name: $temp1 signal
  # - platform: xiaomi_lywsdcgq
  #   mac_address: $temp1_mac
  #   temperature:
  #     name: $temp1_upper temperature
  #     id: ${temp1}_temperature
  #   humidity:
  #     name: $temp1_upper humidity
  #     id: ${temp1}_humidity
  #   battery_level:
  #     name: ${temp1} battery
  #     id: ${temp1}_battery

  # - platform: ble_rssi
  #   mac_address: $plant1_mac
  #   id: $plant1
  #   name: $plant1_upper
  #   disabled_by_default: true
  #   entity_category: diagnostic
  #   device_class: signal_strength
  #   state_class: measurement
  #   unit_of_measurement: dBm
  #   accuracy_decimals: 0

  # - platform: ble_rssi
  #   mac_address: $plant2_mac
  #   id: $plant2
  #   name: $plant2_upper
  #   disabled_by_default: true
  #   entity_category: diagnostic
  #   device_class: signal_strength
  #   state_class: measurement
  #   unit_of_measurement: dBm
  #   accuracy_decimals: 0

  # - platform: ble_rssi
  #   mac_address: $plant3_mac
  #   id: $plant3
  #   name: $plant3_upper
  #   disabled_by_default: true
  #   entity_category: diagnostic
  #   device_class: signal_strength
  #   state_class: measurement
  #   unit_of_measurement: dBm
  #   accuracy_decimals: 0

  # - platform: ble_rssi
  #   mac_address: $plant4_mac
  #   id: $plant4
  #   name: $plant4_upper
  #   disabled_by_default: true
  #   entity_category: diagnostic
  #   device_class: signal_strength
  #   state_class: measurement
  #   unit_of_measurement: dBm
  #   accuracy_decimals: 0

  # - platform: ble_rssi
  #   mac_address: $plant5_mac
  #   id: $plant5
  #   name: $plant5_upper
  #   disabled_by_default: true
  #   entity_category: diagnostic
  #   device_class: signal_strength
  #   state_class: measurement
  #   unit_of_measurement: dBm
  #   accuracy_decimals: 0

  # - platform: ble_rssi
  #   mac_address: $plant6_mac
  #   id: $plant6
  #   name: $plant6_upper
  #   disabled_by_default: true
  #   entity_category: diagnostic
  #   device_class: signal_strength
  #   state_class: measurement
  #   unit_of_measurement: dBm
  #   accuracy_decimals: 0

  # - platform: xiaomi_hhccjcy01
  #   mac_address: $plant1_mac
  #   temperature:
  #     name: $plant1_upper temperature
  #     id: ${plant1}_temperature
  #     filters:
  #     - filter_out: nan
  #     - lambda: return x * (9.0/5.0) + 32.0;
  #     unit_of_measurement: "°C"
  #   moisture:
  #     name: $plant1_upper moisture
  #     icon: mdi:water-percent
  #     id: ${plant1}_moisture
  #     filters:
  #     - filter_out: nan
  #   illuminance:
  #     name: $plant1_upper illuminance
  #     id: ${plant1}_illuminance
  #     filters:
  #     - filter_out: nan
  #   conductivity:
  #     name: $plant1_upper soil conductivity
  #     id: ${plant1}_conductivity
  #     filters:
  #     - filter_out: nan

  # - platform: xiaomi_hhccjcy01
  #   mac_address: $plant2_mac
  #   temperature:
  #     name: $plant2_upper temperature
  #     id: ${plant2}_temperature
  #     filters:
  #     - filter_out: nan
  #     - lambda: return x * (9.0/5.0) + 32.0;
  #     unit_of_measurement: "°C"
  #   moisture:
  #     name: $plant2_upper moisture
  #     icon: mdi:water-percent
  #     id: ${plant2}_moisture
  #     filters:
  #     - filter_out: nan
  #   illuminance:
  #     name: $plant2_upper illuminance
  #     id: ${plant2}_illuminance
  #     filters:
  #     - filter_out: nan
  #   conductivity:
  #     name: $plant2_upper soil conductivity
  #     id: ${plant2}_conductivity
  #     filters:
  #     - filter_out: nan

  # - platform: xiaomi_hhccjcy01
  #   mac_address: $plant3_mac
  #   temperature:
  #     name: $plant3_upper temperature
  #     id: ${plant3}_temperature
  #     filters:
  #     - filter_out: nan
  #     - lambda: return x * (9.0/5.0) + 32.0;
  #     unit_of_measurement: "°C"
  #   moisture:
  #     name: $plant3_upper moisture
  #     icon: mdi:water-percent
  #     id: ${plant3}_moisture
  #     filters:
  #     - filter_out: nan
  #   illuminance:
  #     name: $plant3_upper illuminance
  #     id: ${plant3}_illuminance
  #     filters:
  #     - filter_out: nan
  #   conductivity:
  #     name: $plant3_upper soil conductivity
  #     id: ${plant3}_conductivity
  #     filters:
  #     - filter_out: nan

  # - platform: xiaomi_hhccjcy01
  #   mac_address: $plant4_mac
  #   temperature:
  #     name: $plant4_upper temperature
  #     id: ${plant4}_temperature
  #     filters:
  #     - filter_out: nan
  #     - lambda: return x * (9.0/5.0) + 32.0;
  #     unit_of_measurement: "°C"
  #   moisture:
  #     name: $plant4_upper moisture
  #     icon: mdi:water-percent
  #     id: ${plant4}_moisture
  #     filters:
  #     - filter_out: nan
  #   illuminance:
  #     name: $plant4_upper illuminance
  #     id: ${plant4}_illuminance
  #     filters:
  #     - filter_out: nan
  #   conductivity:
  #     name: $plant4_upper soil conductivity
  #     id: ${plant4}_conductivity
  #     filters:
  #     - filter_out: nan

  # - platform: xiaomi_hhccjcy01
  #   mac_address: $plant5_mac
  #   temperature:
  #     name: $plant5_upper temperature
  #     id: ${plant5}_temperature
  #     filters:
  #     - filter_out: nan
  #     - lambda: return x * (9.0/5.0) + 32.0;
  #     unit_of_measurement: "°C"
  #   moisture:
  #     name: $plant5_upper moisture
  #     icon: mdi:water-percent
  #     id: ${plant5}_moisture
  #     filters:
  #     - filter_out: nan
  #   illuminance:
  #     name: $plant5_upper illuminance
  #     id: ${plant5}_illuminance
  #     filters:
  #     - filter_out: nan
  #   conductivity:
  #     name: $plant5_upper soil conductivity
  #     id: ${plant5}_conductivity
  #     filters:
  #     - filter_out: nan

  # - platform: xiaomi_hhccjcy01
  #   mac_address: $plant6_mac
  #   temperature:
  #     name: $plant6_upper temperature
  #     id: ${plant6}_temperature
  #     filters:
  #     - filter_out: nan
  #     - lambda: return x * (9.0/5.0) + 32.0;
  #     unit_of_measurement: "°C"
  #   moisture:
  #     name: $plant6_upper moisture
  #     icon: mdi:water-percent
  #     id: ${plant6}_moisture
  #     filters:
  #     - filter_out: nan
  #   illuminance:
  #     name: $plant6_upper illuminance
  #     id: ${plant6}_illuminance
  #     filters:
  #     - filter_out: nan
  #   conductivity:
  #     name: $plant6_upper soil conductivity
  #     id: ${plant6}_conductivity
  #     filters:
  #     - filter_out: nan
