---
# Luntak brand Tuya Plug
#
substitutions:
  project: Sound machine
  id: sound_machine
  hostname: "plug-sound-machine"

  <<: !include common/substitutions/gpio/tuya_plug.yaml

<<: !include common/templates/plug_no_status_lights.yaml
