---
# Luntak brand Tuya Plug (plug02)
#
substitutions:
  project: plug02
  id: plug02
  hostname: plug02

  <<: !include common/substitutions/gpio/tuya_plug.yaml

<<: !include common/templates/plug.yaml
