---
# Luntak brand Tuya Plug
#
substitutions:
  project: Hot water pump
  id: hot_water_pump
  hostname: plug-pump
  ip: 10.0.20.65

  off_delay: 10min

  <<: !include common/substitutions/gpio/tuya_plug.yaml

<<: !include common/templates/plug_led_off_delay.yaml
