---
# Luntak brand Tuya Plug
#
substitutions:
  project: Plug07
  id: plug07
  hostname: plug07
  ip: 10.0.20.67

  <<: !include common/substitutions/gpio/tuya_plug.yaml

<<: !include common/templates/plug.yaml
