---
# Luntak brand Tuya Plug
#
substitutions:
  project: Printer
  id: printer
  hostname: plug-printer

  <<: !include common/substitutions/gpio/tuya_plug.yaml

<<: !include common/templates/plug.yaml
