---
# Sonoff S31 Power Monitoring Plug, Always On
#
substitutions:
  project: Bedroom fan power monitor
  id: powerbedroomfan
  hostname: "power-bedroom-fan"
  ip: 10.0.20.30

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor_always_on.yaml
