---
# Sonoff S31 Power Monitoring Plug, Always On
#
substitutions:
  project: Glowforge power monitor
  id: powerglowforge
  hostname: power-glowforge

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor_always_on.yaml
