---
# Sonoff Power Module
#
substitutions:
  project: Sonoff POW 01
  id: sonoffpow01
  hostname: sonoffpow01
  ip: 

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor.yaml
