---
# Sonoff Power Module
#
substitutions:
  project: Sonoff POW 02
  id: sonoff_pow_02
  hostname: sonoff_pow_02

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor.yaml
