---
# Sonoff S31 Power Monitoring Plug, Always On
#
substitutions:
  friendly_name: Glowforge power monitor
  id: powerglowforge
  hostname: power-glowforge
  ip: 10.0.20.43

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor_always_on.yaml
