---
# Sonoff S31 Power Monitoring Plug
#
substitutions:
  project: Dryer power monitor
  id: powerdryer
  hostname: power-dryer

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor_always_on.yaml
