---
# Sonoff S31 Power Monitoring Plug
#
substitutions:
  project: Prusa
  id: powerprusa

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor.yaml