---
# Sonoff Basic Power Module
#
substitutions:
  project: Sonoff Basic 01
  id: sonoff_basic_01
  hostname: sonoff_basic_01

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/plug.yaml
