---
# Sonoff S31 Power Monitoring Plug, Always On
#
substitutions:
  friendly_name: Washing machine power monitor
  comment: sonoff_s31_02
  id: powerwasher
  hostname: power-washer
  #ip: 10.0.20.44

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor_always_on.yaml
