---
# Sonoff Basic Power Module
#
substitutions:
  friendly_name: Sonoff Basic 01
  id: sonoff_basic_01
  hostname: sonoff_basic_01
  comment: Sonoff Basic 01
  #ip: 10.0.20.42

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/plug.yaml
