---
# Sonoff Power Module
#
substitutions:
  project: Sonoff POW 01
  id: sonoff_pow_01

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor.yaml
