---
# Sonoff S31 Power Monitoring Plug, Always On
#
substitutions:
  project: Washing Machine Power Monitor
  id: powerwasher

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor_always_on.yaml