---
# Sonoff S31 Power Monitoring Plug
#
substitutions:
  project: Family room soundbar power monitor
  id: soundbar_power_monitor
  hostname: power-soundbar

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor_always_on.yaml
