---
# Sonoff S31 Power Monitoring Plug
#
substitutions:
  project: Dryer Power Monitor
  id: powerdryer

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor_always_on.yaml