---
# Sonoff S31 Power Monitoring Plug, Always On
#
substitutions:
  project: Washing machine power monitor
  id: powerwasher
  hostname: power-washer

  <<: !include common/substitutions/gpio/sonoff.yaml

<<: !include common/templates/sonoff_power_monitor_always_on.yaml
