substitutions:
  name: "workbench-presence"
  friendly_name: Workbench presence
packages:
  Athom_Technology.Presence_Sensor: github://athom-tech/athom-configs/athom-presence-sensor.yaml
esphome:
  friendly_name: ${friendly_name}
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret encryption_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
