---
# https://esphome.io/devices/nodemcu_esp32.html
esphome:
  friendly_name: $friendly_name
  name: $hostname
  comment: $comment

esp32:
  board: nodemcu-32s
  framework:
    version: recommended
  restore_from_flash: true
