---
esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m

<<: !include ../wifi.yaml
<<: !include ../ota.yaml
<<: !include ../api.yaml
<<: !include ../logger.yaml

binary_sensor:
  - !include ../binary_sensors/power_button_inverted.yaml

switch:
  - !include ../switches/relay.yaml
