---
esphome:
  name: $hostname
  platform: ESP8266
  board: esp01_1m

  <<: !include ../esphome/leds/status.yaml

<<: !include ../wifi.yaml
<<: !include ../ota.yaml
<<: !include ../api.yaml
<<: !include ../logger.yaml

binary_sensor:
  - !include ../binary_sensors/power_button_inverted.yaml

light:
  - !include ../lights/status_led.yaml

output:
  - !include ../outputs/status_led.yaml

switch:
  - !include ../switches/relay_internal.yaml
  - !include ../switches/relay_status_led.yaml
