---
esphome:
  name: $id
  platform: ESP8266
  board: esp01_1m

<<: !include ../wifi.yaml
<<: !include ../ota.yaml
<<: !include ../api.yaml

<<: !include ../power_monitor_logger_uart.yaml

sensor:
  <<: !include ../sensors/power_monitor_cse7766.yaml

switch:
  <<: !include ../switches/relay_always_on_internal.yaml
