---
on_boot:
  priority: -100.0
  then:
    # Set light to half brightness when first ready.
    - light.turn_on:
        id: status_led
        brightness: 50%

    # Wait to check for a Home Assistant API connection.
    - delay: 15s
    - if:
        condition:
          api.connected:
        then:
          # If connected, then flash the LED, and leave it at full brightness.
          - logger.log: "$friendly_name is connected to the Home Assistant API!"
          - light.turn_on:
              id: status_led
              brightness: 100%
          - delay: 0.5s
          - light.turn_off: status_led
          - delay: 0.5s
          - light.turn_on:
              id: status_led
              brightness: 100%
          - delay: 0.5s
          - light.turn_off: status_led
          - delay: 0.5s
          - light.turn_on:
              id: status_led
              brightness: 100%
          - delay: 0.5s
          - light.turn_off: status_led
          - delay: 0.5s
          - light.turn_on:
              id: status_led
              brightness: 100%

# Turn off the LED when the device is shutting down (like for a firmware update).
on_shutdown:
  then:
    - light.turn_off: status_led
